# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 376b6dac0a49d50f07e708387e057f373ac192bc5dfbe2f90e673161a78521c49859789f84594246baba68a9398b488b7f365f513a196f071a5d1f080cb98aa5

test:
  secret_key_base: eca98f267547693b90075538778f2216405597668ef3f01063e124e6844f127ee0be3c37478c3f9cfcfa2cd92162871a11bfc5549a747b141d47f2c835879d6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
